### PR TITLE
make target for ui-build

### PR DESCRIPTION
**Pull request by sibyl229**
This will probably save you sometime and worry about ui code building. 

If you wonder why I use `-l` a login shell, it's because nvm does not work without it: https://github.com/nvm-sh/nvm/issues/1446

### CODE REVIEW

**Comment by mgrbyte** [comment]
For me, this doesn't work - because I use `zsh` and the NVM environment vars have been put (by the tooling) into `~/.zshrc`. 

Possible solutions:
1. Have the user (me in this case!)  install nvm in bash as well (or copy env vars from $NOT_BASH_SHELL env to `~/.bash_profile` one)

2. Figure out a way of making `make` work across shells with this nvn problem (yuk, tricky).

3. Simple solution; bake the nvm env vars into the script, have the Makefile call the script.

I'd be inclined to go with 3, what do you think?

**Review by mgrbyte — COMMENTED** [review]
For me, this doesn't work - because I use `zsh` and the NVM environment vars have been put (by the tooling) into `~/.zshrc`. 

Possible solutions:
1. Have the user (me in this case!)  install nvm in bash as well (or copy env vars from $NOT_BASH_SHELL env to `~/.bash_profile` one)

2. Figure out a way of making `make` work across shells with this nvn problem (yuk, tricky).

3. Simple solution; bake the nvm env vars into a  script (e.g client/build.sh), and have the top-level Makefile call the script.

I'd be inclined to go with 3, what do you think?

**Comment by sibyl229** [comment]
@mgrbyte Ah, I see. I didn't think about different shells. I pushed a change implementing Option 3. Does it work for you?

**Comment by mgrbyte** [comment]
> @mgrbyte Ah, I see. I didn't think about different shells. I pushed a change implementing Option 3. Does it work for you?

No, doesn't work (for the same reason - `NVM_DIR` env var is not set in my shell).
I think the script _could_ set it itself.

I put togther e595402d1d0205c8b754eb46735331521cd1b9aa , which works for me.

Otherwise we'll need to add something to the README about setting up nvm in bash as dev requirement.

**Review by mgrbyte — CHANGES_REQUESTED** [review]
Can we add the env vars that as per my comment on the thread for this PR?

**Comment by sibyl229** [comment]
@mgrbyte yup! I cherry picked your NVM_DIR commit to this branch.

**Pull request merged**
