### PR TITLE
fixes #104 content-type for svg and other static files

### LINKED ISSUE #104: Problem serving SVG
The wormbase logo shows up as a broken image. But it loads fine if you go to the URL for the image directly `/static/media/icon.58f8d16b.svg`.

Not sure if this is related to the content-type header problem described here: https://css-tricks.com/snippets/htaccess/serve-svg-correct-content-type/

### PR DESCRIPTION
**Pull request by sibyl229**

### CODE REVIEW

**Review by mgrbyte — COMMENTED** [review]
~Right solution :+1~: 
Style nit-picks, prefer either:
`(wrap-content-type (wrap-resource handler "client_build")`
or 
`(-> handler (wrap-resource "client_biuld") wrap-content-type)`

**Comment by mgrbyte** [comment]
Actually, this doesn't work.
`ring-resource/wrap-resource` will return a response for resource if a route  matches, else delegate to the handler.  Cannot uniformly apply the content-type middleware since the the handler uses a different content type (application/json) which isn't set until a later middleware comes into play.

**Comment by sibyl229** [comment]
@mgrbyte It's definitely a concern that those middleware would interfere with each other. Is there a way to check whether the middleware is causing problems? I tried these following cases and they all seem to work as expected (_assuming ring is deployed on port 4010_) : 
- http://lvh.me:4010/gene/id/WBGene00303228 (404 -> index.html)
- http://lvh.me:4010/api/gene/WBGene00303228 (API JSON)
- http://lvh.me:4010/asset-manifest.json (static JSON)

**Comment by mgrbyte** [comment]
@sibyl229  Seems to be working for me now, must of had some stale state somewhere :confused:

**Comment by mgrbyte** [comment]
@sibyl229 Still think #107 makes sense, what do you think?

**Comment by sibyl229** [comment]
@mgrbyte I don't have a strong preference one way or the other. Feel free to go ahead with nginx if you like. Just make sure everything in the `client/build` folder is being served.

**Pull request merged**
