### PR TITLE
fix handling of static resource

### LINKED ISSUE #225: Unable to render site
@sibyl229 Tested #224 locally and was all good, but when deploying via jar file/docker, (something) causes the site not to be rendered due to a js file having html in it.

names-js-error

Any ideas what might cause this? (REST API and swagger /api-docs  is working fine)

### PR DESCRIPTION
**Pull request by sibyl229**
fixes #225 

@mgrbyte I think this should fix the problem of serving static assets

### CODE REVIEW

**Comment by mgrbyte** [comment]
@sibyl229 thanks for testing and putting this together!

The breakage seems to have come out of the recent auth-all-endpoints work.

I changed the middleware organisation to make API docs work in this branch at 7997659

But: the google auth is failing.

Something to do with the recent API being called too soon i think? 
Behaviour is the google sign-in  pop up closes when you click login, before you have a chance to select account.
The actual request to the google endpoint returns 200. Chrome Inspector screenshot below to illustrate

names_google-signin_issue

**Review by mgrbyte — COMMENTED** [review]
:+1: Added a commit to make api-docs work
the authentication is applied at the `/api` level

**Comment by sibyl229** [comment]
Hi @mgrbyte maybe there is a bigger issue that's beyond the scope of static resource loading, which this PR is about. I have problem creating genes (needed for testing recent activities), getting a 500 error, with the latest code from this branch and DB of datomic:ddb://us-east-1/WSNames/05032019 . Shall we work on the various other issues on separate branches?

**Review by mgrbyte — APPROVED** [review]

**Comment by mgrbyte** [comment]
Note: this issue was caused due to manually tinkering with JS deps with node, which "corrupted" the client app, subsequently replacing the local checkout,  then forgetting about the giti-gnored google credentials files in `resources/config`.

**Pull request merged**
