### PR TITLE
Feature/generic entity api

### PR DESCRIPTION
**Pull request by mgrbyte**
Hi @sibyl229 , this should be the last big "feature" before the 1st proper release.
The changes  in this PR are two fold:

1. _A method for dynamically adding new (simple) entity types to the system_
    A simple entity is conceptually a mapping, that consists of the keys:

   * “id”
   * “status”
   * “name”
   The swagger UI lists these “new” generic endpoints with the tag “entity”.

   Implementation notes
   Some restrictions have been imposed to due to the nature of the modelling employed and the invariants of the datomic database system.

  Generic entity types:
  * Are described in the response to a call to “GET /api/entity”
    * The key/property “generic?” will be set to true if it’s a generic entity type. 
 Example: 

 ```json
{
  "entity-types": [
    {
      "entity-type": "gene",
      "generic?": false,
      "enabled?": true
    },
    {
      "entity-type": "sequence-feature",
      "generic?": true,
      "enabled?": true
    },
    {
      "entity-type": "variation",
      "generic?": true,
      "enabled?": true
    }
  ]
}
 ```
    * The tabs for entities on the directory page could potentially be built from the above data,
      and associated request controllers.  
  * Once added to the system, it cannot be removed, or renamed (datomic schema cannot be retracted)
  * Cannot be removed, nor renamed
  * Can be enabled or disabled. When disabled, endpoints with the entity type in the URL will return an error response. Each generic entity endpoint checks if the entity is “enabled” before allowing requests to proceed.

2. _Request and response key/property renaming_
   * All keys in the request payloads and response bodies are now plain strings (no longer are string representations of the clojure/datomic ident/keyword.  e.g: `{..., "id": "WBGene000000001"}`
    * All values for enumerations (e.g biotype) are now plain strings, e.g `{..., "biotype": "cds"}`

### CODE REVIEW

**Comment by sibyl229** [comment]
Hi @mgrbyte I pushed the UI changes to the same branch. I'm not sure if this is what you expect, but I think it was the easiest way to test the API and UI code together. I'm open to suggestions, if you have other ideas.

I have only tested the UI on variations so far, since adding a gene is blocked by the `/api/species` problem. 

I also noticed a 500 error with `/api/entity`: `"java.lang.IllegalArgumentException"`. I will continue the work on dynamically populating the entity types once this is fixed.

**Comment by sibyl229** [comment]
Hi @mgrbyte I pushed the UI changes to the same branch. I'm not sure if this is what you expect, but I think it was the easiest way to test the API and UI code together. I'm open to suggestions, if you have other ideas.

I have only tested the UI on variations so far, since adding a gene is blocked by the `/api/species` problem. 

I also noticed a 500 error with `/api/entity`: `"java.lang.IllegalArgumentException"`. I will continue the work on dynamically populating the entity types once this is fixed.

**Comment by sibyl229** [comment]
ToDo list for myself:
- [ ] rebase on `master` and resolve conflict on this branch
- [x] testing gene related operations, including autocompletion
- [ ] creating a gene without cgc-name seems to fail, preventing the testing of gene merge
- [ ] testing split and merge event display in gene history: split event seems to miss information on the other gene
- [x] code and testing dynamical entity types
- [ ] remove mock code for `/api/entity`, once the endpoint works
- [ ] creating a sequence feature seems to fail with a spec problem
- [ ] testing recent activity (doesn't work with in-memory databases)

**Comment by mgrbyte** [comment]
> Hi @mgrbyte I pushed the UI changes to the same branch. I'm not sure if this is what you expect, but I think it was the easiest way to test the API and UI code together. I'm open to suggestions, if you have other ideas.
> 
> I have only tested the UI on variations so far, since adding a gene is blocked by the `/api/species` problem.
> 
> I also noticed a 500 error with `/api/entity`: `"java.lang.IllegalArgumentException"`. I will continue the work on dynamically populating the entity types once this is fixed.

I'm not seeing the 500 error with /api/entity (tested with memory db), can you post the traceback in slack pls?

**Comment by mgrbyte** [comment]
@sibyl229  I think I've now fixed all the issues above and some more.
Was missing some test cases and hadn't fully manually tested species and stats; both should now work.
The `/api/entity` endpoint giving 500 I'm hoping was a red-herring - works in the tests,
and manually via curl here.

**Comment by sibyl229** [comment]
@mgrbyte thanks for looking into this! Here is the error I'm getting for `/api/entity`
```
11:26:47.411 ERROR compojure.api.exception [qtp870781669-57]

java.lang.IllegalArgumentException: null
	at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:111)
	at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:37)
	at com.google.api.client.json.webtoken.JsonWebSignature$Parser.parse(JsonWebSignature.java:599)
	at com.google.api.client.googleapis.auth.oauth2.GoogleIdToken.parse(GoogleIdToken.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
	at wormbase.names.auth$parse_token.invokeStatic(auth.clj:41)
	at wormbase.names.auth$parse_token.invoke(auth.clj:40)
	at wormbase.names.auth$identify.invokeStatic(auth.clj:95)
	at wormbase.names.auth$identify.invoke(auth.clj:93)
	at buddy.auth.backends.token$token_backend$reify__36532._authenticate(token.clj:89)
	at buddy.auth.middleware$authenticate_request.invokeStatic(middleware.clj:39)
	at buddy.auth.middleware$authenticate_request.invoke(middleware.clj:25)
	at buddy.auth.middleware$authentication_request.invokeStatic(middleware.clj:49)
	at buddy.auth.middleware$authentication_request.doInvoke(middleware.clj:42)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at buddy.auth.middleware$wrap_authentication$fn__36560.invoke(middleware.clj:59)
	at buddy.auth.middleware$wrap_authorization$fn__36567.invoke(middleware.clj:110)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__20514.invoke(keyword_params.clj:53)
	at ring.middleware.params$wrap_params$fn__5001.invoke(params.clj:67)
	at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__40010.invoke(absolute_redirects.clj:47)
	at ring.middleware.content_type$wrap_content_type$fn__26561.invoke(content_type.clj:34)
	at ring.middleware.default_charset$wrap_default_charset$fn__39982.invoke(default_charset.clj:31)
	at ring.middleware.not_modified$wrap_not_modified$fn__26594.invoke(not_modified.clj:61)
	at wormbase.db$wrap_datomic$fn__32337.invoke(db.clj:77)
	at ring.middleware.resource$wrap_resource_prefer_resources$fn__39927.invoke(resource.clj:25)
	at ring.middleware.content_type$wrap_content_type$fn__26561.invoke(content_type.clj:34)
	at ring.middleware.gzip$wrap_gzip$fn__42878.invoke(gzip.clj:94)
	at compojure.api.middleware$wrap_swagger_data$fn__22601.invoke(middleware.clj:190)
	at compojure.api.middleware$wrap_inject_data$fn__22579.invoke(middleware.clj:96)
	at muuntaja.middleware$wrap_params$fn__21576.invoke(middleware.clj:52)
	at compojure.api.middleware$wrap_exceptions$fn__22568.invoke(middleware.clj:62)
	at muuntaja.middleware$wrap_format_request$fn__21588.invoke(middleware.clj:114)
	at compojure.api.middleware$wrap_exceptions$fn__22568.invoke(middleware.clj:62)
	at muuntaja.middleware$wrap_format_response$fn__21592.invoke(middleware.clj:132)
	at muuntaja.middleware$wrap_format_negotiate$fn__21585.invoke(middleware.clj:96)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__20514.invoke(keyword_params.clj:53)
	at ring.middleware.nested_params$wrap_nested_params$fn__20572.invoke(nested_params.clj:89)
	at ring.middleware.params$wrap_params$fn__5001.invoke(params.clj:67)
	at compojure.api.middleware$wrap_inject_data$fn__22579.invoke(middleware.clj:96)
	at compojure.api.routes.Route.invoke(routes.clj:89)
	at clojure.lang.Var.invoke(Var.java:381)
	at ring.middleware.reload$wrap_reload$fn__2753.invoke(reload.clj:39)
	at ring.middleware.stacktrace$wrap_stacktrace_log$fn__1210.invoke(stacktrace.clj:26)
	at ring.middleware.stacktrace$wrap_stacktrace_web$fn__1276.invoke(stacktrace.clj:96)
	at ring.adapter.jetty$proxy_handler$fn__486.invoke(jetty.clj:25)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

```

**Review by mgrbyte — COMMENTED** [review]
:+1:

**Review by sibyl229 — APPROVED** [review]

**Pull request merged**
