### PR TITLE
Swap merge event labels to to reflect change in #306.

### LINKED ISSUE #308: REST API gene merge event labels are reversed for recent merges
Due to the changes made in #306.
events described as "merged into" should be "merged from" and vice-versa.

### PR DESCRIPTION
**Pull request by mgrbyte**
Fixes #308

### CODE REVIEW

**Comment by mluypaert** [comment]
If I understand the logic correctly (not 100% sure), the dead gene should get "merged into" another gene. The gene that remains alive gets info "merged from" the dead gene. This logic is independent from which gene has the Datomic `:gene/merges` attribute assigned, and hence would not be affected by switching the merge reference from side (done in PR #307).

When looking at the test website (which does not have the code above implemented yet), the merge testing case seems to follow the logic above and looks to be represented fine to me.
image

So to my opinion, this fix is not needed (and incorrect) and should be discarded (along with issue #308).

**Review by mluypaert — COMMENTED** [review]
If I understand the logic correctly (not 100% sure), the dead gene should get "merged into" another gene. The gene that remains alive gets info "merged from" the dead gene. This logic is independent from which gene has the Datomic `:gene/merges` attribute assigned, and hence would not be affected by switching the merge reference from side (done in PR #307).

When looking at the test website (which does not have the code above implemented yet), the merge testing case seems to follow the logic above and looks to be represented fine to me.
image

So to my opinion, this fix is not needed (and incorrect) and should be discarded (along with issue #308).

**Comment by mgrbyte** [comment]
> If I understand the logic correctly (not 100% sure), the dead gene should get "merged into" another gene. The gene that remains alive gets info "merged from" the dead gene. This logic is independent from which gene has the Datomic `:gene/merges` attribute assigned, and hence would not be affected by switching the merge reference from side (done in PR #307).
> 
Exactly correct.

> When looking at the test website (which does not have the code above implemented yet), the merge testing case seems to follow the logic above and looks to be represented fine to me.
> image
> 
> So to my opinion, this fix is not needed (and incorrect) and should be discarded (along with issue #308).

I had already deployed the change to the test-system web site (tag:wormbase-names-1.4.2), 
hence the PR :+1:

**Comment by mluypaert** [comment]
> I had already deployed the change to the test-system web site (tag:wormbase-names-1.4.2),
> hence the PR 👍

Release 1.4.2 does not contain the commit intended to be merge here AFAIK.
* Release 1.4.2 has been created 2 days ago, while commit 13480b5625 was only created 5 hours ago
* Running `git tag --contains 13480b5625` should return all tags this commit is contained in, but returns nothing.

So unless you create a dirty EB deployment (is that possible?), this commit has not been deployed to test-system website yet.

**Comment by mgrbyte** [comment]
> > I had already deployed the change to the test-system web site (tag:wormbase-names-1.4.2),
> > hence the PR +1
> 
> Release 1.4.2 does not contain the commit intended to be merge here AFAIK.
> 

The release `wormbase-names-1.4.2` contains the [change](3f278e213d9c6de1f077664e008d95b7937ae34f) to upgrade the dependency on `wormbase/ids`, which brings in the new behaviour.
 
> * Release 1.4.2 has been created 2 days ago, while commit [13480b5](https://github.com/WormBase/names/commit/13480b5625caafd3d57ad51061f339b17b301d57) was only created 5 hours ago
> * Running `git tag --contains 13480b5625` should return all tags this commit is contained in, but returns nothing.
> 
> So unless you create a dirty EB deployment (is that possible?), this commit has not been deployed to test-system website yet.

The commit you reference here is in the branch `bugfix/merge-event-labels` (#309), so won't yet be part of any tag (not merged to master, not tagged or released).

**Comment by mluypaert** [comment]
> The release `wormbase-names-1.4.2` contains the [change](3f278e213d9c6de1f077664e008d95b7937ae34f) to upgrade the dependency on `wormbase/ids`, which brings in the new behaviour.

> 
> The commit you reference here is in the branch `bugfix/merge-event-labels` (#309), so won't yet be part of any tag (not merged to master, not tagged or released).

@mgrbyte I think your mixing up two different PRs/Issues here. PR #307 (fixing issue #306) contained the commit 3f278e21 (which you refer to) already, which got merged into master and closed. Those are fine, no arguments there anymore.

This PR (#309, issue #308) contains only one commit 13480b56, and is intended to merge branch `bugfix/merge-event-labels` back into master. These changes are not release yet, and are here the point of discussion.
As the "merged into" and "merged from" labels on the current test-environment website seem to be implemented fine to me (see my [initial comment](https://github.com/WormBase/names/pull/309#pullrequestreview-450682744)), there no need to fix anything or reverse the labeling logic. So to my insight, PR #309 (this one) should be closed without merging and issue #308 discarded, as there is no issue with the merge event labels and the proposed changes in commit 13480b56 would actually break things.

**Comment by mgrbyte** [comment]
> > The release `wormbase-names-1.4.2` contains the [change](3f278e213d9c6de1f077664e008d95b7937ae34f) to upgrade the dependency on `wormbase/ids`, which brings in the new behaviour.
> 
> > The commit you reference here is in the branch `bugfix/merge-event-labels` (#309), so won't yet be part of any tag (not merged to master, not tagged or released).
> 
> @mgrbyte I think your mixing up two different PRs/Issues here. PR #307 (fixing issue #306) contained the commit [3f278e2](https://github.com/WormBase/names/commit/3f278e213d9c6de1f077664e008d95b7937ae34f) (which you refer to) already, which got merged into master and closed. Those are fine, no arguments there anymore.
> 
> This PR (#309, issue #308) contains only one commit [13480b5](https://github.com/WormBase/names/commit/13480b5625caafd3d57ad51061f339b17b301d57), and is intended to merge branch `bugfix/merge-event-labels` back into master. These changes are not release yet, and are here the point of discussion.
> As the "merged into" and "merged from" labels on the current test-environment website seem to be implemented fine to me (see my [initial comment](https://github.com/WormBase/names/pull/309#pullrequestreview-450682744)), there no need to fix anything or reverse the labeling logic. So to my insight, PR #309 (this one) should be closed without merging and issue #308 discarded, as there is no issue with the merge event labels and the proposed changes in commit [13480b5](https://github.com/WormBase/names/commit/13480b5625caafd3d57ad51061f339b17b301d57) would actually break things.

OK, having looked at this twice now I can see your correct (I've gotten very confused with these labels). 
Sorry for the noise!

**Pull request closed without merging**
