### PR TITLE
at least 7 diget prefix of WBID to triger autocompletion

### PR DESCRIPTION
**Pull request by sibyl229**

### CODE REVIEW

**Review by mgrbyte — APPROVED** [review]

**Review by mgrbyte — APPROVED** [review]

**Comment by mgrbyte** [comment]
Also think the server should do something similar to prevent accidental consumption of resources.
Wonder what you think: 
 would be preferable if the API returned a different kind of response for these "minimum prefix" issue (either a different status, say HTTP 100 continue, or some other marker in the response data) 
or just implement the same prefix checking.

**Comment by sibyl229** [comment]
@mgrbyte It's definitely desirable for the API to protect itself from accidental depletion of resource. 

I'm kind of ambivalent on how the response status code and structure should be, whether these response should be handled as an error (with no-2xx status) or as a regular empty response, but potentially with a message indicating the reason for being empty. What do you think?

**Comment by mgrbyte** [comment]
> @mgrbyte It's definitely desirable for the API to protect itself from accidental depletion of resource.
> 
> I'm kind of ambivalent on how the response status code and structure should be, whether these response should be handled as an error (with no-2xx status) or as a regular empty response, but potentially with a message indicating the reason for being empty. What do you think?

Yes, think that's the best approach:
A 200 response with empty "matches" entry, but a message/reason entry describing why empty results are returned is probably what I'll go with. 
I'll implement something along those lines as PR for you to review shortly.

**Comment by sibyl229** [comment]
@mgrbyte that works great for me. Thanks!

**Pull request merged**
